name: onedrive
description: Manage files on OneDrive
version: 0.1.0
repository: https://github.com/alex-relov/onedrive

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  dio: ^5.7.0
  json_annotation: ^4.9.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.13
  json_serializable: 6.8.0
